<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var string $name
 * @var array $menu
 * @var null|array|string|bool $activeUrl
 * @var bool $noNav
 * @var string $render May be "breadcrumbs" or "menu".
 * @var \Laminas\View\Helper\Navigation $nav
 *
 * Options for Laminas Navigation
 *
 * Specific options to render as "menu" (default):
 * @var string|null $partial
 * @var string|int $indent
 * @var int|null $minDepth
 * @var int|null $maxDepth
 * @var string $ulClass
 * @var string $liActiveClass
 * @var bool $onlyActiveBranch
 * @var bool $renderParents
 * @var bool $escapeLabels
 * @var bool $addClassToListItem
 *
 * Specific options to render as "breadcrumbs":
 * @var string|null $partial
 * @var string|int $indent
 * @var int|null $minDepth
 * @var string $separator Default "&gt;".
 * @var bool $linkLast
 *
 * @link https://docs.laminas.dev/laminas-navigation/helpers/menu
 *
 * And any other options passed through the helper.
 */

if (!$nav) return;
?>

<?php if ($render === 'breadcrumbs'):

    echo $partial
        ? $nav->breadcrumbs()->renderPartialWithParams($this->vars()->getArrayCopy(), null, $partial)
        : $nav->breadcrumbs()
            ->setIndent($indent)
            ->setMinDepth($minDepth)
            ->setSeparator($separator)
            ->setLinkLast($linkLast)
            ->renderStraight();

else:

    echo $partial
        ? $nav->menu()->renderPartialWithParams($this->vars()->getArrayCopy(), null, $partial)
        : $nav->menu()->renderMenu(null, $this->vars()->getArrayCopy());

endif;
