<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Site\Navigation\Link\LinkInterface $link
 * @var ?array $data
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');

$data = empty($data) ? [] : $data;
$label = $data['label'] ?? null;
$id = $data['id'] ?? null;
$resource = null;
$resourceLabel = null;
if ($id) {
    try {
        $resource = $this->api()->read('resources', ['id' => $id])->getContent();
        $resourceLabel = $resource->displayTitle();
    } catch (Exception $e) {
    }
}
?>

<label><?= $translate('Type'); ?>
    <input type="text" value="<?= $escape($translate($link->getName())) ?>" disabled="disabled"/>
</label>
<?php if ($resource): ?>
<label><?= $escape($translate(ucfirst(str_replace('-', ' ', $resource->getControllerName())))) ?>
    <input type="text" value="<?= $escape($resourceLabel) ?>" disabled="disabled"/>
</label>
<?php endif; ?>
<label><?= $translate('Label'); ?>
    <input type="text" data-name="label" value="<?= $escape($label) ?>"/>
</label>
<label><?= $translate('Resource id') ?>
    <input type="number" data-name="id" value="<?= $id ? (int) $id : '' ?>" min="1" required="required"/>
    <?php if ($id && !$resource): ?>
    <span style="float: right; color: red; font-weight: normal;"><?= $escape($translate('Resource unavailable')) ?></span>
    <?php endif; ?>
</label>
